DROP TRIGGER verif_logement ON LOGEMENT;
DROP TRIGGER creation_contrat ON CONTRAT;
DROP TRIGGER verif_dates_contrat ON CONTRAT;
DROP TRIGGER contrat_fini ON CONTRAT;
DROP TABLE PROPRIETAIRE,LOGEMENT,DEMANDEUR,CAUTIONNAIRE,SERVICE,ASSOCIE,CONTRAT CASCADE;

DROP DOMAIN types,prestations_logement,taches CASCADE;
